server:
  port: 9001
spring:
  profiles: Drew
  datasource:
    password: kkh753
  application:
    name: database
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:9000/eureka}
---
spring:
  profiles: Danya
  datasource:
    password: xna004
---
spring:
  profiles:
    active: Drew