server:
  port: 9002
spring:
  profiles: Drew, Danya
  main:
    allow-bean-definition-overriding: true
  application:
    name: database
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:9000/eureka}
    healthcheck:
      enabled: true
  instance:
    health-check-url: ${server.servletPath}/health
---
spring:
  profiles: Danya
  datasource:
    password: xna004
---
spring:
  profiles: Drew
  datasource:
    password: kkh753
---
spring:
  profiles:
    active: Drew